### ISSUE TITLE
iOS 9.3 - not working

### ISSUE THREAD

**Issue by JulesMoorhouse** [sdarlington/WSLViewAutoDismiss#3]
I'm not getting any errors, however the alert doesn't display.

I'd like to keep iOS 7.1 and above.

However 1.0.1 doesn't seem to work.

I've tried 1.0.0 but I get to following podfile error...
[!] Unable to satisfy the following requirements:
- `WSLViewAutoDismiss (= 1.0.0)` required by `Podfile`
- `WSLViewAutoDismiss (= 1.0.0)` required by `Podfile`

Help would be much appreciated.

Thanks in advance.

**Comment by sdarlington** [comment]
Did you try the demo app? It's working for me in iOS 10 so I'd be surprised if it failed in iOS 9.x.

**Comment by JulesMoorhouse** [comment]
I've just tried the demo, and it does work.

Confused.
I've just tried a backup from June and that worked, with version 1.0.

Thanks for your reply.
